{{- if .Values.compactionDescheduler.enabled -}}
{{- $resourceName := printf "%s-compaction-descheduler" (include "kubex-automation-engine.fullname" .) -}}
{{- $configName := "kubex-compaction-descheduler-config" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $resourceName }}
  labels:
    {{- include "kubex-automation-engine.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $resourceName }}
  labels:
    {{- include "kubex-automation-engine.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $resourceName }}
    namespace: {{ include "kubex-automation-engine.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubex-automation-engine.fullname" . }}-manager-role
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $resourceName }}
  labels:
    {{- include "kubex-automation-engine.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.compactionDescheduler.schedule | quote }}
  suspend: {{ .Values.compactionDescheduler.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "kubex-automation-engine.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ $resourceName }}
          containers:
            - name: descheduler
              image: {{ .Values.compactionDescheduler.image.repository }}:{{ .Values.compactionDescheduler.image.tag }}
              imagePullPolicy: {{ .Values.compactionDescheduler.image.pullPolicy }}
              args:
                - --policy-config-file=/policy/policy.yaml
                - --v=4
              volumeMounts:
                - name: policy
                  mountPath: /policy
              resources:
                {{- toYaml .Values.compactionDescheduler.resources | nindent 16 }}
          volumes:
            - name: policy
              configMap:
                name: {{ $configName }}
                items:
                  - key: policy.yaml
                    path: policy.yaml
{{- end -}}
