kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: e2e-gpu
nodes:
  - role: control-plane
  - role: worker
    labels:
      nvidia.com/gpu.present: "true"
    extraMounts:
      - hostPath: /proc
        containerPath: /physical-host-proc
        readOnly: true
