---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-vanilla
---
apiVersion: rightsizing.kubex.ai/v1alpha1
kind: AutomationStrategy
metadata:
  name: gpu-vanilla-strategy
  namespace: gpu-vanilla
spec:
  experimental:
    gpuKaiContract: v1alpha1-2026-04
  enablement:
    gpu:
      requests:
        downsize: true
        upsize: true
        setFromUnspecified: false
---
apiVersion: rightsizing.kubex.ai/v1alpha1
kind: StaticPolicy
metadata:
  name: gpu-vanilla-policy
  namespace: gpu-vanilla
spec:
  scope:
    labelSelector:
      matchLabels:
        app: gpu-vanilla-demo
  resources:
    containers:
      "*":
        requests:
          cpu: 200m
          memory: 256Mi
          gpu: "0.7"
        limits:
          cpu: 600m
          memory: 1Gi
  automationStrategyRef:
    name: gpu-vanilla-strategy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-vanilla-demo
  namespace: gpu-vanilla
  labels:
    app: gpu-vanilla-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-vanilla-demo
  template:
    metadata:
      labels:
        app: gpu-vanilla-demo
    spec:
      containers:
        - name: app
          image: busybox:1.37
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
              nvidia.com/gpu: 2
            limits:
              cpu: 700m
              memory: 1200Mi
              nvidia.com/gpu: 2
