kind: CronJob
schedule: "0 0 1 1 *"
suspend: true

nodeSelector:
  scheduling.kubex.ai/role: busy-a

cmdOptions:
  v: 4

deschedulerPolicyAPIVersion: descheduler/v1alpha2
deschedulerPolicy:
  maxNoOfPodsToEvictPerNode: 1
  maxNoOfPodsToEvictPerNamespace: 1
  maxNoOfPodsToEvictTotal: 1
  profiles:
    - name: gke-poc
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: false
            labelSelector:
              matchLabels:
                scheduling.kubex.ai/binpack: "true"
        - name: HighNodeUtilization
          args:
            thresholds:
              cpu: 60
              memory: 25
              pods: 100
            numberOfNodes: 0
      plugins:
        balance:
          enabled:
            - HighNodeUtilization
