apiVersion: rightsizing.kubex.ai/v1alpha1
kind: ClusterCompactionPolicy
metadata:
  name: compaction-test
spec:
  scope:
    namespaceSelector:
      operator: NotIn
      values:
        - "kube-system"
        - "kubex"
    workloadTypes:
      - Deployment
  scheduler:
    useKubexScheduler: true
  descheduler:
    enabled: true
    interval: "* * * * *"
    maxNoOfPodsToEvictPerNode: 2
    maxNoOfPodsToEvictPerNamespace: 2
    maxNoOfPodsToEvictTotal: 2
    highNodeUtilization:
      thresholds:
        cpu: 70
        memory: 70
        pods: 70
